name = "d1p"
main = "src/index.js"
compatibility_date = "2025-09-10"

[[d1_databases]]
binding = "D1_SUNE"
database_name = "sune"
database_id = "140c5f3d-c4d4-4cdf-b520-a23366172971"

[[d1_databases]]
binding = "D1_HI"
database_name = "hi"
database_id = "45ee691d-3d0c-42f2-8e3a-35a369444a03"

